name: paper_explainer
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.11.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - huggingface
  - transformers